# Generated by Django 5.2 on 2025-04-21 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='specifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specification_name', models.CharField(max_length=100)),
                ('parameter', models.CharField(max_length=100)),
                ('limit', models.CharField(max_length=50)),
            ],
        ),
    ]
