# Generated by Django 5.2 on 2025-04-21 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(max_length=200)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('author', models.CharField(max_length=100)),
                ('remarks', models.TextField(blank=True)),
            ],
        ),
    ]
