# Generated by Django 5.2 on 2025-04-21 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='batches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=100, unique=True)),
                ('product_name', models.CharField(max_length=200)),
                ('manufacture_date', models.DateField()),
                ('expiry_date', models.DateField()),
            ],
        ),
    ]
