# Generated by Django 5.2 on 2025-04-21 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='samples',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('collected_on', models.DateField()),
            ],
        ),
    ]
